-- Proyecto LIDIA - roles logicos EC3. Ejecutar con un rol administrador.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'lidia_dashboard') THEN
        CREATE ROLE lidia_dashboard NOLOGIN;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'lidia_etl') THEN
        CREATE ROLE lidia_etl NOLOGIN;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'lidia_admin') THEN
        CREATE ROLE lidia_admin NOLOGIN;
    END IF;
END
$$;

GRANT USAGE ON SCHEMA dw TO lidia_dashboard;
GRANT SELECT ON ALL TABLES IN SCHEMA dw TO lidia_dashboard;
ALTER DEFAULT PRIVILEGES IN SCHEMA dw GRANT SELECT ON TABLES TO lidia_dashboard;

GRANT USAGE ON SCHEMA staging, dw, audit TO lidia_etl;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA staging, dw, audit TO lidia_etl;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA staging, dw, audit TO lidia_etl;
ALTER DEFAULT PRIVILEGES IN SCHEMA staging GRANT SELECT, INSERT, UPDATE ON TABLES TO lidia_etl;
ALTER DEFAULT PRIVILEGES IN SCHEMA dw GRANT SELECT, INSERT, UPDATE ON TABLES TO lidia_etl;
ALTER DEFAULT PRIVILEGES IN SCHEMA audit GRANT SELECT, INSERT, UPDATE ON TABLES TO lidia_etl;
ALTER DEFAULT PRIVILEGES IN SCHEMA staging GRANT USAGE, SELECT ON SEQUENCES TO lidia_etl;
ALTER DEFAULT PRIVILEGES IN SCHEMA dw GRANT USAGE, SELECT ON SEQUENCES TO lidia_etl;
ALTER DEFAULT PRIVILEGES IN SCHEMA audit GRANT USAGE, SELECT ON SEQUENCES TO lidia_etl;

GRANT ALL PRIVILEGES ON SCHEMA staging, dw, audit TO lidia_admin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA staging, dw, audit TO lidia_admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA staging, dw, audit TO lidia_admin;
